openapi: 3.0.0

info:
  title: Now Transact
  version: v0.0.1
  description: API sepcification for the now-transact application

servers:
  - url: /api

paths:
  /users:
    post:
      summary: Create a user
      tags: [User]
      requestBody:
        description: Create a user
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Successfully created user
  /users/{user_id}:
    get:
      summary: Retrieve a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Successfully retrieved user by id

components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phonenumber:
          type: string
        password:
          type: string
  parameters:
    user_id:
      in: path
      description: id of user to be retrieved
      name: user_id
      required: true
      schema:
        type: number
