openapi: 3.0.0

info:
  title: Now Transact
  version: v0.0.1
  description: API sepcification for the now-transact application

servers:
  - url: /api/v1

paths:
  /users:
    post:
      summary: Create a user
      tags: [User]
      requestBody:
        description: User to create
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Successfully created user
  /users/{user_id}:
    get:
      summary: Retrieve a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Successfully retrieved user
    put:
      summary: Update a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      requestBody:
        description: User to update
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/UpdateUser'
      responses:
        200:
          description: Successfully retrieved user
    delete:
      summary: Delete a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Successfully deleted user
  /auth:
    post:
      summary: Authenticate user and receive token
      tags: [User, Auth]
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        201:
          description: Successfully authenticated user

components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phonenumber:
          type: string
        password:
          type: string
    UpdateUser:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phonenumber:
          type: string
    AuthCredentials:
      type: object
      properties:
        id:
          type: integer
        password:
          type: string
  parameters:
    user_id:
      in: path
      description: id of user to be retrieved
      name: user_id
      required: true
      schema:
        type: number
