openapi: 3.0.0

info:
  title: Now Transact
  version: v0.0.1
  description: API sepcification for the now-transact application

servers:
  - url: /api/v1

paths:
  /users:
    post:
      summary: Create a user
      tags: [User]
      requestBody:
        description: User to create
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Successfully created user
  /users/{user_id}:
    get:
      summary: Retrieve a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Successfully retrieved user
    put:
      summary: Update a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      requestBody:
        description: User to update
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/UpdateUser'
      responses:
        200:
          description: Successfully retrieved user
    delete:
      summary: Delete a user by id
      tags: [User]
      parameters:
        - $ref: '#/components/parameters/user_id'
      responses:
        200:
          description: Successfully deleted user
  /auth:
    post:
      summary: Authenticate user and receive token
      tags: [Auth]
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        201:
          description: Successfully authenticated user
  /accounts:
    post:
      summary: Create an account
      tags: [Account]
      requestBody:
        description: Account creation payload
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: Successfully created account
  /accounts/{account_id}:
    get:
      summary: Retrieve an account
      tags: [Account]
      parameters:
        - $ref: '#/components/parameters/account_id'
      responses:
        200:
          description: Successfully retrieved account
    put:
      summary: Update an account
      tags: [Account]
      parameters:
        - $ref: '#/components/parameters/account_id'
      requestBody:
        description: Account update payload
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/Account'
      responses:
        200:
          description: Successfully created account
    delete:
      summary: Delete an account
      tags: [Account]
      parameters:
        - $ref: '#/components/parameters/account_id'
      responses:
        200:
          description: Successfully deleted account
  /accounts/{account_id}/transactions:
    post:
      operationId: 'app.controllers.transactions.post' # manually specified to limit ambiguity
      summary: Make a transaction
      tags: [Transaction]
      parameters:
        - $ref: '#/components/parameters/account_id'
      requestBody:
        description: Transaction creation payload
        required: true
        content:
          application/json:
            schema:
              x-body-name: payload
              $ref: '#/components/schemas/Transaction'
      responses:
        200:
          description: Successfully executed transaction
    get:
      operationId: 'app.controllers.transactions.search'
      summary: Fetch transactions, accepts query search params
      tags: [Transaction]
      parameters:
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/description'
      responses:
        200:
          description: Successfully fetched transactions

components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phonenumber:
          type: string
        password:
          type: string
    UpdateUser:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
        phonenumber:
          type: string
    AuthCredentials:
      type: object
      properties:
        user_id:
          type: integer
        password:
          type: string
    Account:
      type: object
      properties:
        account_name:
          type: string
    Transaction:
      type: object
      properties:
        transaction_amount:
          type: string
        transaction_description:
          type: string
        transaction_type:
          type: string
  parameters:
    user_id:
      in: path
      description: id of user
      name: user_id
      required: true
      schema:
        type: integer
    account_id:
      in: path
      description: id of account
      name: account_id
      required: true
      schema:
        type: integer
    offset:
      in: query
      description: offset for pagination
      name: offset
      schema:
        type: integer
    limit:
      in: query
      description: limit per page for pagination
      name: limit
      schema:
        type: integer
    description:
      in: query
      description: transaction description
      name: description
      schema:
        type: string
