"""Add account model

Revision ID: 002b95e55fe1
Revises: 7661dd4652d9
Create Date: 2023-02-27 02:53:34.127067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002b95e55fe1'
down_revision = '7661dd4652d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('account_number', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('account_holder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_holder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
