"""Add origin_ip

Revision ID: 0f80526efbf4
Revises: 81c19b56875b
Create Date: 2023-02-28 17:33:00.693186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f80526efbf4'
down_revision = '81c19b56875b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_ip', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('origin_ip')

    # ### end Alembic commands ###
